config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  
  resources :users, only: %i[new create]
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Items < ApplicationRecord
  belongs_to :user
  # has_many :item_tags, dependent: :destroy
  # has_many :tags, through: :item_tags

  validates :title, presence: true, length: { maximum: 255 }
  validates :item_url, presence: true, length: { maximum: 255 }
  # 説明欄は必須ではない
  validates :description, length: { maximum: 255 }, allow_blank: true

  def youtube_video_id
    uri = URI.parse(self.item_url)
    uri.path.split('/').last
  end

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 255 }

  has_many :items, dependent: :destroy

  def own?(item)
    self.id == item.user_id
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, danger: "ログインしてください"
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[edit update destroy]

  def index
    # @items = Item.includes(:user).order(created_at: :desc)
    @items = current_user.items.order(created_at: :desc)
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def edit
    @item = current_user.items.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to items_url, success: t('items.create.success')
    else
      flash.now[:danger] = t('items.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @item = current_user.items.find(params[:id])
    if @item.update(item_params)
      redirect_to items_url(@item), success: t('defaults.flash_message.updated', item: Item.model_name.human)
    else
      flash.now[:danger] = t('defaults.flash_message.not_updated', item: Item.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    item = current_user.items.find(params[:id])
    item.destroy!
    redirect_to items_url, success: t('defaults.flash_message.deleted', item: Item.model_name.human), status: :see_other
  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :item_url)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    skip_before_action :require_login, only: %i[top]

    def top; end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to root_path, success: t('user_sessions.create.success')
    else
      flash.now[:danger] = t('user_sessions.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
      logout
      flash[:danger] = t('user_sessions.destroy.success')
      redirect_to root_path, status: :see_other
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
    # ↓あえてroot_pathにリダイレクトさせる
    redirect_to root_path, success: t('users.create.success')
    else
      flash.now[:danger] = t('users.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<div class="row">
  <div class="col-lg-8 offset-lg-2">
    <%= render 'shared/error_messages', object: @item %>
    <%= form_with model: @item do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: '例：心臓マッサージ' %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <div> 
        【タグが入る行】
      </div>
      <div> 
        YouTube shortsの動画URLを貼りつけてください
      </div>
      <div class="form-group">
        <%= f.label :item_url %>
        <%= f.text_field :item_url, class: 'form-control', id: 'item_url' %>
      </div>
      <div class="actions">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
      <div id="preview"></div>
    <% end %>
  </div>
</div>

app/views/items/_item.html.erb
<div class="col-sm-5 col-lg-4 mb-3">
  <div id="post-id-<%= item.id %>">
    <div class="card">
      <%= link_to item_path(item), class: "btn", data: { turbo: false } do %>
        <div class="card-body text-center">
          <iframe
            width="180" 
            height="320" 
            src="https://www.youtube.com/embed/<%= item.youtube_video_id %>" 
            frameborder="0" 
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
            allowfullscreen>
          </iframe>
          <div class="row">
            <div class="col-12">
              <%= item.title %>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              [タグ]
            </div>
          </div>
          <div class="row">
            <div class="col-6">
              [送るボタン]
            </div>
            <div class="col-6">
              <%= link_to t('defaults.show'), item_path(item) %> 
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<h1><%= t('.title') %></h1>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
    <%= render 'form', { item: @item } %>
    </div>
  </div>
</div>

<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>

<% if flash[:danger] %>
  <div class="alert alert-danger">
    <%= flash[:danger] %>
  </div>
<% end %>

app/views/items/index.html.erb
<h1><%= t('.title') %></h1>
<div class="container pt-3">
  <!-- 検索フォーム -->
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <form>
        <div class="input-group mb-3"><input class="form-control" placeholder="検索ワード" type="search"/>
          <div class="input-group-append"><input type="submit" value="検索" class="btn btn-primary"/></div>
        </div>
      </form>
        <%# <%= render 'search', q: @q, url: boards_path %> <%# ゆくゆくはこっちを使うかも%>
    </div>
  </div>
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @items.present? %>
    		  <%= render @items %>
		    <% else %>
		      <p><%= t('defaults.flash_message.no_item') %></p>
		    <% end %>
        <%# <%= paginate @items, theme: 'bootstrap-5' %> 
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<h1><%= t('.title') %></h1>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <%= render 'form', { item: @item } %>
    </div>
  </div>
</div>

<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>

<% if flash[:danger] %>
  <div class="alert alert-danger">
    <%= flash[:danger] %>
  </div>
<% end %>

app/views/items/show.html.erb
<h1><%= t('.title') %></h1>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <article class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-3">
              <iframe
              width="180" 
              height="320" 
              src="https://www.youtube.com/embed/<%= @item.youtube_video_id %>" 
              frameborder="0" 
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
              allowfullscreen>
              </iframe>
            </div>
            <div class="col-md-9">
              <h3 style="display: inline;"><%= @item.title %></h3>
              <ul class="list-inline">
                <%= @item.description %>
              </ul>
              <ul class="list-inline">
                <%= @item.item_url %>
              </ul>
              <ul class='d-flex justify-content-end'>
                <li class="list-inline-item">
                  <%= link_to t('defaults.edit'), edit_item_path(@item), id: "button-edit-#{@item.id}" %>
                </li>
                <li class="list-inline-item">
                  <%= link_to t('defaults.delete'), item_path(@item),
                              id: "button-delete-#{@item.id}",
                              method: :delete,
                              data: { turbo_method: :delete, turbo_confirm: t('defaults.flash_message.delete_confirm') } %>
                </li>
              </ul>
            </div>
          </div>
        </article>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= yield %>
      <%= render 'shared/footer' %>
      <%= javascript_include_tag 'item_preview' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.png" %>
    <% end %>

    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
          <li class="nav-item">
              <%= link_to t('header.login'), login_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p>Copyright © 2024 Emergency C+</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to '/', class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to t('header.item'), '#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-item-menu' %>
          <div class='dropdown-menu dropdown-menu-end'>
            <%= link_to t('header.item_index'), items_path, class: 'dropdown-item' %>
            <%= link_to t('header.create_item'), '/items/new', class: 'dropdown-item' %>
          </div>
        </li>

        <li class='nav-item'>
        <%# ↓　dones_path %>
          <%= link_to t('header.done_index'), "#", class: 'nav-link' %>
        </li>

        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to '#', class: 'nav-link', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-profile' do %>
            <%= current_user.name %>
          <% end %>
          <div class='dropdown-menu dropdown-menu-end'>
            <div class='dropdown-divider'></div>
             <%= link_to t('header.user_show'), user_path(current_user), class: 'dropdown-item' %>
             <%= link_to t('header.logout'), logout_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/static_pages/top.html.erb
<div class='top-wrapper'>
  <div class='top-inner-text'>
    <h1>このアプリでできること</h1>
    <%= image_tag "top.jpg" %>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1><%= t('.title') %></h1>
      <%= form_with url: login_path do |f| %>
        <div class="mb-3">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <%= f.submit t('.login'), class: "btn btn-primary" %>
      <% end %>
      <div class='text-center'>
        <%= link_to t('.to_register_page'), new_user_path %>
        <%= link_to t('.password_forget'), "#" %> <%# ← new_password_reset_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1>ユーザー登録</h1>
      <%= form_with model: @user do |f| %>
      <%# <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :name %> 
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit '登録', class: 'btn' %>
      <% end %>
      <div class='text-center'>
        <%= link_to 'ログインページへ', login_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>